### ISSUE TITLE
When would the dataset details and download url be available?

### ISSUE THREAD

**Issue by TyroneLi** [UnsupervisedSemanticSegmentation/ImageNet-S#1]

**Comment by gasvn** [comment]
Thanks for your interest in our work. This work is still under review. We plan to release it after the reviewing process for now.
If we release it early than expected, I will notice you in this issue.

**Comment by niladridutt** [comment]
Can you give an ETA please? @gasvn

**Comment by gasvn** [comment]
Sorry for the waiting, our dataset is now released.
